---
# tasks file for htpc-manager

- name: Install Package Requirements
  package:
     name: "{{ item }}"
     state: present
  with_items:
    - python-cheetah
    - git
    - sqlite3
    - python-pip
    - python-dev
    - apache2

- name: Install latest psutils with pip
  pip: name=psutil

- name: Get HTPC-Manager Code from GitHub
  git:
    repo: "{{ htpc_manager_repo }}"
    dest: "{{ htpc_manager_path }}"

- name: Make sure HTPC-Manager directory has correct ownership
  file: 
    path: "{{ htpc_manager_path }}"
    owner: "{{ htpc_user_username }}"
    group: "{{ htpc_user_group }}"
    recurse: yes

- name: Update HTPC-Manager init.d script
  template: 
    src: "init.{{ ansible_os_family }}"
    dest: "/etc/init.d/{{ htpc_manger_init_script }}"
    owner: root 
    group: root 
    mode: 0755

- name: Make sure HTPC-Manager starts on boot
  service: 
    name: "{{ htpc_manger_init_script }}"
    state: started  
    pattern: '/usr/bin/python Htpc.py' 
    enabled: yes

- name: Stop HTPC-Manager daemon for configuration update
  service: 
    name: "{{ htpc_manger_init_script }}"
    state: stopped  
    pattern: '/usr/bin/python Htpc.py' 
    enabled: yes

- name: Upload HTPC-Manager configuration
  template: 
    src: htpc_manager_config_db.j2 
    dest: /tmp/htpc_manager_config.db 
    owner: "{{ htpc_user_username }}"

- name: check if database was already configured
  stat:
    path: "{{ htpc_manager_path }}/ansible_check"
  register: ansible_check

- name: Drop HTPC-Manager database
  file: 
    path: "{{ htpc_manager_path }}/userdata/database.db"
    state: absent
  when: ansible_check.stat.exists == False

- name: Update HTPC-Manager configuration database
  become: yes
  become_user: "{{ htpc_user_username }}"
  shell: cat /tmp/htpc_manager_config.db | sqlite3 {{ htpc_manager_path }}/userdata/database.db
  when: ansible_check.stat.exists == False

- name: touching file
  file:
    path: "{{ htpc_manager_path }}/ansible_check"
    state: touch
  when: ansible_check.stat.exists == False

- name: Start HTPC-Manager
  service: 
    name: "{{ htpc_manger_init_script }}"
    state: started 
    pattern: '/usr/bin/python Htpc.py' 
    enabled: yes

- name: Enable apache proxy modules
  apache2_module: 
    name: "{{ item }}"
    state: present
  with_items:
    - proxy
    - proxy_http

- name: Disable default apache site
  file: 
    path: /etc/apache2/sites-enabled/000-default.conf 
    state: absent

- name: Add HTPC-Manager VirtualHost
  template: 
    src: apache_htpc-manager.conf 
    dest: /etc/apache2/sites-available/htpc-manager.conf

- name: Enable apache2 reverse proxy for HTPC-Manager
  file: 
    src: /etc/apache2/sites-available/htpc-manager.conf 
    dest: /etc/apache2/sites-enabled/htpc-manager.conf 
    state: link

- name: Restart Apache
  service: 
    name: apache2 
    state: restarted