---

- name: restart apache
  service: 
    name: apache2 
    state: restarted

- name: restart htpc-manager
  systemd:
    state: restarted
    name: htpc-manager.service

- name: stop htpc-manager
  systemd:
    state: stopped
    name: htpc-manager.service
